### ISSUE TITLE
CA Gages

### ISSUE THREAD

**Issue by ksonda** [dblodgett-usgs/ref_gages#13]
compilation of gages going on here, including a rigorous, manually-checked snapping to reachcodes and COMIDs

https://gispublic.waterboards.ca.gov/portal/home/item.html?id=32dfb85bd2744487affe6e3475190093#overview

In next two months will have a version being served out as OAF w/ landing pages

**Comment by ksonda** [comment]
https://sb19.linked-data.internetofwater.dev/collections/ca_gages/items?f=json&limit=10000

vars of interest:

uri = geoconnex pid
comid = geoconnex comid pid
comid_medres = nhdplusv2 line segement COMID
totdasqkm = Total drainage area in square kilometers
totdasqmi = Total drainage area in square miles
rchcd_medres = nhdplusv2 reachcode

**Comment by dblodgett-usgs** [comment]
I added these in: https://github.com/dblodgett-usgs/ref_gages/commit/a22771aeec9992e11a2301ff033cb4c942802050

For those that do not have measures, I add them here: https://github.com/dblodgett-usgs/ref_gages/blob/master/R/gage_locations.R#L86
